### ISSUE TITLE
Not Handling Zoom Properly with VideoRecorderActivity

### ISSUE THREAD

**Issue by commonsguy** [commonsguy/cwac-cam2#154]
There is no zoom support for `VideoRecorderActivity`, so something is amiss here:

```
Caused by: java.lang.ClassCastException: java.lang.Boolean cannot be cast to com.commonsware.cwac.cam2.ZoomStyle
                                                       at com.commonsware.cwac.cam2.CameraFragment.getZoomStyle(CameraFragment.java:452)
                                                       at com.commonsware.cwac.cam2.CameraFragment.onCreateView(CameraFragment.java:203)

```

See https://stackoverflow.com/q/35584464/115145 for more.

**Comment by commonsguy** [comment]
Addressed in v0.5.1.
