### ISSUE TITLE
Could not dispatch event:

### ISSUE THREAD

**Issue by saefbadwan** [commonsguy/cwac-cam2#331]
Android version 4.4 kitkat
Device note 4

Could not dispatch event: class com.commonsware.cwac.cam2.CameraEngine$OrientationChangedEvent to subscribing class class com.commonsware.cwac.cam2.CameraController
                                                                 java.lang.RuntimeException: set display orientation failed
                                                                     at android.hardware.Camera.setDisplayOrientation(Native Method)
                                                                     at com.commonsware.cwac.cam2.plugin.OrientationPlugin$Classic.configureStillCamera(OrientationPlugin.java:149)
                                                                     at com.commonsware.cwac.cam2.ClassicCameraEngine$Session.configureStillCamera(ClassicCameraEngine.java:618)
                                                                     at com.commonsware.cwac.cam2.ClassicCameraEngine.handleOrientationChange(ClassicCameraEngine.java:409)
                                                                     at com.commonsware.cwac.cam2.CameraController.onEventMainThread(CameraController.java:428)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
                                                                     at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:420)
                                                                     at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:397)
                                                                     at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:370)
                                                                     at org.greenrobot.eventbus.EventBus.post(EventBus.java:251)
                                                                     at com.commonsware.cwac.cam2.plugin.OrientationPlugin$1.onOrientationChanged(OrientationPlugin.java:55)
                                                                     at android.view.OrientationEventListener$SensorEventListenerImpl.onSensorChanged(OrientationEventListener.java:143)
                                                                     at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:455)
                                                                     at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                     at android.os.MessageQueue.next(MessageQueue.java:143)
                                                                     at android.os.Looper.loop(Looper.java:130)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5942)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

**Comment by commonsguy** [comment]
Per [the documentation](https://github.com/commonsguy/cwac-cam2/blob/master/.github/CONTRIBUTING.md), please provide:

- the `Build.MANUFACTURER` and `Build.PRODUCT` values for the hardware on which you are experiencing the problem
- the code necessary to reproduce the problem (this could be one of the demo apps, or it could be some demo project of yours that you publish)
- the steps necessary, using that code and that hardware, to reproduce the problem
