### ISSUE TITLE
Demo app doesn't work

### ISSUE THREAD

**Issue by bruferrari** [commonsguy/cwac-cam2#335]
I'm looking forward to a new library to work with a camera on my woking project so I found this one, but the demo app refuse to work properly, here goes the stacktrace:
```
08-08 10:48:51.490 13976-13976/com.commonsware.cwac.cam2.demo E/ActivityThread: Activity com.commonsware.cwac.cam2.demo.MainActivity has leaked ServiceConnection android.media.MediaScannerConnection@fcbb8fd that was originally bound here
                                                                                android.app.ServiceConnectionLeaked: Activity com.commonsware.cwac.cam2.demo.MainActivity has leaked ServiceConnection android.media.MediaScannerConnection@fcbb8fd that was originally bound here
                                                                                    at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1336)
                                                                                    at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1231)
                                                                                    at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1450)
                                                                                    at android.app.ContextImpl.bindService(ContextImpl.java:1422)
                                                                                    at android.content.ContextWrapper.bindService(ContextWrapper.java:636)
                                                                                    at android.media.MediaScannerConnection.connect(MediaScannerConnection.java:119)
                                                                                    at android.media.MediaScannerConnection.scanFile(MediaScannerConnection.java:238)
                                                                                    at com.commonsware.cwac.cam2.demo.MainActivity.delete(MainActivity.java:503)
                                                                                    at com.commonsware.cwac.cam2.demo.MainActivity.onDestroy(MainActivity.java:152)
                                                                                    at android.app.Activity.performDestroy(Activity.java:6874)
                                                                                    at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1175)
                                                                                    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4195)
                                                                                    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4226)
                                                                                    at android.app.ActivityThread.-wrap6(ActivityThread.java)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1534)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)```

Device: Lenovo MotoG5 / Android 7.0

**Comment by commonsguy** [comment]
That's not really a problem in the app. The app works fine, but I am a bit sloppy in handling the indexing of the resulting files.

That being said, use CameraKit-Android or Fotoapparat, instead of this library, as I will be discontinuing work on it shortly.
