### ISSUE TITLE
Autofocus failed runtime exception

### ISSUE THREAD

**Issue by VBegoyan** [commonsguy/cwac-cam2#338]
Hi, i am experiencing with this issue: 
Received device exception during capture call: 
                                                                     java.lang.RuntimeException: autoFocus failed
                                                                         at android.hardware.Camera.native_autoFocus(Native Method)
                                                                         at android.hardware.Camera.autoFocus(Camera.java:1300)
                                                                         at android.hardware.camera2.legacy.LegacyFocusStateMapper.processRequestTriggers(LegacyFocusStateMapper.java:205)
                                                                         at android.hardware.camera2.legacy.RequestThreadManager$5.handleMessage(RequestThreadManager.java:824)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                         at android.os.Looper.loop(Looper.java:234)
                                                                         at android.os.HandlerThread.run(HandlerThread.java:61)

Device is: Sony D6503, Android 6.0.1, Api 23

**Comment by VBegoyan** [comment]
Forget to mention, that i am working on Camera2

**Comment by commonsguy** [comment]
As is noted on the project home page, this project is discontinued.
Please use another library, such as Fotoapparat or CaneraKit-Android.

On Fri, Nov 10, 2017, at 06:15, Vardges Begoyan wrote:
> Forget to mention, that i am working on Camera2
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/commonsguy/cwac-cam2/issues/338#issuecomment-343446897


-- 
Mark Murphy (a Commons Guy)
https://commonsware.com | https://github.com/commonsguy
https://commonsware.com/blog | https://twitter.com/commonsguy
